In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

df = pd.read_csv('Pizza.csv')

In [2]:
features = df.columns[2:]
features

Index(['mois', 'prot', 'fat', 'ash', 'sodium', 'carb', 'cal'], dtype='object')

In [3]:
m = df[features].mean()
centered_data = df[features] - df[features].mean()
centered_data

mois      prot        fat       ash  sodium       carb    cal
0   -13.083067  8.056433  24.640467  2.476767  1.1006 -22.094767  1.659
1   -12.413067  7.886433  23.660467  2.706767  1.1206 -21.844767  1.569
2   -12.553067  6.616433  25.550467  2.446767  0.9606 -22.064767  1.679
3   -10.353067  6.776433  22.900467  2.156767  0.9406 -21.484767  1.469
4   -10.413067  7.906433  21.420467  2.186767  0.9706 -21.104767  1.399
..         ...       ...        ...       ...     ...        ...    ...
295   4.006933 -2.303567  -3.229533 -0.143233 -0.0094   2.495233 -0.361
296   2.246933 -1.583567  -1.769533 -0.203233  0.0006   1.305233 -0.171
297   3.646933 -2.363567  -4.199533 -0.203233 -0.0294   3.115233 -0.351
298   6.696933 -2.943567  -5.049533 -0.313233 -0.1094   1.605233 -0.511
299   5.936933 -3.463567  -4.729533 -0.363233 -0.0994   2.615233 -0.461

[300 rows x 7 columns]

In [58]:
pca = PCA(n_components=2)
principal_components = pca.fit_transform(centered_data)

# 主成分方向向量
w1, w2 = pca.components_
w1, w2

(array([-2.76963426e-01, -2.66941457e-01, -2.78933559e-01, -5.54340960e-02,
        -1.11416057e-02,  8.78084364e-01, -6.03287596e-04]),
 array([-0.74707368,  0.05573295,  0.65784531,  0.04060421,  0.02381376,
        -0.00681755,  0.06125383]))

In [56]:
S = centered_data.T @ centered_data
S

mois          prot           fat          ash       sodium  \
mois    27286.606579   6620.931419  -4392.180771   963.107725  -108.197648   
prot     6620.931419  12379.020084   8599.552199  2012.485340   305.765542   
fat     -4392.180771   8599.552199  24088.170135  2697.559853   927.666616   
ash       963.107725   2012.485340   2697.559853   482.047164   113.626282   
sodium   -108.197648    305.765542    927.666616   113.626282    41.012292   
carb   -30477.235685 -29606.890400 -30979.050433 -6153.518024 -1238.217242   
cal     -1353.847520     83.809030   1272.239240    76.848830    46.137080   

                carb         cal  
mois   -30477.235685 -1353.84752  
prot   -29606.890400    83.80903  
fat    -30979.050433  1272.23924  
ash     -6153.518024    76.84883  
sodium  -1238.217242    46.13708  
carb    97196.196684   -78.49803  
cal       -78.498030   114.94830

In [61]:
eigenvalues_S, eigenvectors_S = np.linalg.eig(S)
idx = eigenvalues_S.argsort()[::-1]  # 降序排序
eigenvalues_S_sorted = eigenvalues_S[idx]
eigenvectors_S_sorted = eigenvectors_S[:, idx]

print("Sorted Eigenvalues of S:", eigenvalues_S_sorted[:2])
w1 = eigenvectors_S_sorted[:, 0]
w2 = eigenvectors_S_sorted[:, 1]


Sorted Eigenvalues of S: [126054.97349741  30444.24702927]


In [77]:
x1 = df[features][:1].to_numpy()[0]
x2 = df[features][1:2].to_numpy()[0]

In [78]:
x1, x2

(array([27.82, 21.43, 44.87,  5.11,  1.77,  0.77,  4.93]),
 array([28.49, 21.26, 43.89,  5.34,  1.79,  1.02,  4.84]))

In [85]:
a11 = (x1-m).T @ w1
a12 = (x1-m).T @ w2
a21 = (x2-m).T @ w1
a22 = (x2-m).T @ w2
a11, a12, a21, a22

(24.951747905872786,
 -26.811667755251506,
 24.611975753342847,
 -25.659563399700513)

In [90]:
appx1 = m + a11 * w1 + a12 * w2
appx2 = m + a21 * w1 + a22 * w2
appx1.tolist(), appx2.tolist()

([27.783496937785824,
  21.528515895614635,
  44.82734294963899,
  5.105077523179664,
  1.5858891661232533,
  0.7722370677048186,
  4.928370353002659],
 [28.550099320064316,
  21.373606450091597,
  43.97466265199188,
  5.039462273317961,
  1.5546676217611726,
  1.078440212283421,
  4.8575945711637])

In [91]:
np.linalg.norm(x1 - appx1)**2

array([27.82, 21.43, 44.87,  5.11,  1.77,  0.77,  4.93])