In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

import matplotlib.pyplot as plt

df = pd.read_csv('Pizza.csv')
dfABC = df[(df['brand']=='A') | (df['brand']=='B') | (df['brand']=='C')]
X = dfABC.iloc[:, 2:].to_numpy()
Y = dfABC.iloc[:, 0]

In [25]:
# A vs BC
YA = Y.map({'A':1, 'B':-1, 'C':-1})
svm = SVC(kernel='linear', C=1.0, random_state=42)
svm.fit(X, YA)
wA = svm.coef_
bA = svm.intercept_

In [28]:
# B vs AC
YB = Y.map({'A':-1, 'B':1, 'C':-1})
svm = SVC(kernel='linear', C=1.0, random_state=42)
svm.fit(X, YB)
wB = svm.coef_
bB = svm.intercept_

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1], dtype=int64)

In [29]:
# C vs AB
YC = Y.map({'A':-1, 'B':-1, 'C':1})
svm = SVC(kernel='linear', C=1.0, random_state=42)
svm.fit(X, YC)
wC = svm.coef_
bC = svm.intercept_

In [30]:
s1 = np.array([49.29, 24.82, 21.68, 2.76, 0.52, 1.47, 3.00])
s2 = np.array([30.95, 19.81, 42.28, 5.11, 1.67, 1.85, 4.67])
s3 = np.array([50.33, 13.28, 28.43, 3.58, 1.03, 4.38, 3.27])

In [42]:
s = np.array([s1, s2, s3])
w = np.array([wA[0], wB[0], wC[0]])
b = np.array([bA, bB, bC])

In [60]:
s @ w.T, s @ w.T + b.T

(array([[-2.10470887,  2.25297853,  1.8605257 ],
        [ 0.67449569,  1.66902492, -0.86891194],
        [-2.04952333,  4.59870174, -1.3317382 ]]),
 array([[-1.32874251, -1.16984084,  1.36040938],
        [ 1.45046205, -1.75379446, -1.36902825],
        [-1.27355697,  1.17588237, -1.83185451]]))

In [62]:
print('wA and bA are respectively')
print(wA)
print(bA)
print('-----------------------------------------------')
print('wB and bB are respectively')
print(wB)
print(bB)
print('-----------------------------------------------')
print('wC and bC are respectively')
print(wC)
print(bC)


wA and bA are respectively
[[-0.08337843  0.02314028  0.06481282  0.00903022  0.00384769 -0.01360488
   0.00620176]]
[0.77596636]
-----------------------------------------------
wB and bB are respectively
[[ 1.14713811e-01 -1.66949615e-01  3.38913915e-02 -8.77824409e-03
   9.74604384e-05  2.71226561e-02 -2.67806239e-03]] [-3.42281938]
-----------------------------------------------
wC and bC are respectively
[[-0.01674098  0.19812401 -0.09580719 -0.00745718 -0.01431877 -0.07811867
  -0.00392921]] [-0.50011631]
